### ISSUE TITLE
Details to correct in the documentation

### ISSUE THREAD

**Issue by evatosco** [casanova-lab/NHC#1]
Hello,

I was reading the documentation and I've run the test commands after cloning the code. I noticed that the file extensions are wrong on all examples of the readme file (.pyc instead of .py) and a small erratum ("test_contorls.txt" instead of "test_controls.txt").

I hope this comment is useful, not so much for experts, but for programming beginners and the general public.

Thank you for your work!

**Comment by zhangpeng1202** [comment]
Hi, evissima. Thanks for your interest and your careful reading! Typos are now corrected. ;)
