### ISSUE TITLE
Issues when running large files

### ISSUE THREAD

**Issue by evatosco** [casanova-lab/NHC#2]
Hello there,

I have been inspecting NHC a little bit further. I have run the test data and it works fine. I have used files with 6 lines (6 cases, 6 controls, 6 lines of 5 PCs per line), and it works perfectly, in case_only mode as well as case_control mode.
However, things change when I try case_control mode with 67 cases and around 841 controls, (PC file is 910 lines long):

``` 
Network-based Heterogenity Clustering 
           (Case - Control)           
#######################################
>> Loading Data
Traceback (most recent call last):
  File "NHC_case_control.py", line 85, in <module>
    pc_dict[item[0]] = item[1] + '\t' + item[2] + '\t' + item[3]
IndexError: list index out of range
```
Maybe it is because the files are too long. Test data runs correctly. Other mock data runs correclty.
Checked file paths too, just in case. They are correct. I tried with **NHC-boost**. Same error. In a different line, but same one.

```                 
               < BOOST >             
 Network-based Heterogenity Clustering 
           (Case - Control)           
#######################################
>> Loading Data
Traceback (most recent call last):
  File "NHC-boost_case_control.py", line 86, in <module>
    pc_dict[item[0]] = item[1] + '\t' + item[2] + '\t' + item[3]
IndexError: list index out of range
```
I have read somewhere that this error indicates Python is searching for a non-existent element or item in a list, but I certainly do not know how to fix that, so I am afraid I have no suggestions. I wish I could be more helpful.

It is weird that this error is only shown when using this data in long text files. NHC works okay with other data. 
I have also tried case_only mode with the cases file (67), and with the controls file (841), separately, to see if it runs okay, and it apparently does. I do not know if it would be an issue with the PC file. I checked, it has the same format as the test PC file.

Thank you!!

**Comment by zhangpeng1202** [comment]
Hi, evissima,
Thank you very much for your message and for sharing your experience! I suspect the PC file has some problem: in column 2-4 for three PCs, are there empty value, or alphabets, or something that is not numerical. Is your PC file tab delimited?
Thanks! Let me know. :)

**Comment by evatosco** [comment]
Hi! Thank you for the response!

Yes, in my tab-delimited PC file there are missing values, marked as dots (.). If I replace them with ones (1), just like the documentation says, can I be sure they mean the same thing for NHC as missing values?

Thanks!

**Comment by evatosco** [comment]
Hello again!

I have used another dataset with a PC file without missing values, and the error kept showing. I have read again your response and tried to reduce the PC file from 5 principal component values (6 columns) to 3 principal component (4 columns), even though the test PC file contains 6 columns. It starts to run and initiates the clustering process, at least.

In conclusion: for some reason, in short files, 5 PCs are valid, just as in the test file, but not anymore in larger files.

Sorry for the inconvenience and thank you so much for your availability!

**Comment by zhangpeng1202** [comment]
Thanks very much for your notes. The PC file could have > 3 PCs, but the program will only take the first 3 for computation. The code should be able to handle larger files, as we tested in our in-house datasets. Do you mind sending me your large PC file for checking (zhangpeng1202@gmail.com)? Thanks again!

**Comment by casanova-lab** [comment]
The user solved the issue when switching to another computer.

**Comment by evatosco** [comment]
Update: I found out what the problem was. It was about the input files. For future references:
This error alerts for a discordance between the total of lines in the input files and the total of lines in the PC file. For example, if the case input file has 5 lines and the control input file has 4 lines, but the PC file does not have 9 lines, this error message appears.

Thank you for your patience! I hope it's helpful!

**Comment by zhangpeng1202** [comment]
Yes. The PC file should present PCs for all individuals from cases and controls. Thank you for the update!
